version: '3.7'

services:
  lunchapp:
    image: justtill/where_to_eat:where_to_eat_v.1.0.2
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn LightningLunch.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SQL_ENGINE=django.db.backends.postgresql
      - DATABASE=postgres
      - SQL_DATABASE=${DATABASE_NAME}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_PORT=5432
      - SQL_HOST=db
    depends_on:
      - db
  db:
    image: postgres:11.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  nginx:
    image: justtill/where_to_eat:nginx_latest
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - lunchapp

volumes:
  postgres_data:
  static_volume:
  media_volume: