version: '3.7'

services:
  lunchApp:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:11.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lightning_lunch
      - POSTGRES_PASSWORD=lightning_lunch
      - POSTGRES_DB=lightning_lunch

volumes:
  postgres_data: