# Generated by Django 2.2.7 on 2020-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(choices=[('website_name', 'website_name'), ('background_image', 'background_image'), ('openweathermap_api_key', 'openweathermap_api_key'), ('slack_app_api_key', 'slack_app_api_key'), ('slack_channel', 'slack_channel'), ('city_for_weather', 'city_for_weather')], default=[('website_name', 'website_name'), ('background_image', 'background_image'), ('openweathermap_api_key', 'openweathermap_api_key'), ('slack_app_api_key', 'slack_app_api_key'), ('slack_channel', 'slack_channel'), ('city_for_weather', 'city_for_weather')], max_length=50, unique=True)),
                ('string_property', models.CharField(blank=True, max_length=500, null=True)),
                ('image_property', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
