# Generated by Django 2.2.7 on 2020-01-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='key_name',
            field=models.CharField(choices=[('website_name', 'website_name'), ('background_image', 'background_image'), ('openweathermap_api_key', 'openweathermap_api_key'), ('slack_app_api_key', 'slack_app_api_key'), ('slack_channel', 'slack_channel'), ('city_for_weather', 'city_for_weather'), ('website_url', 'website_url')], default=[('website_name', 'website_name'), ('background_image', 'background_image'), ('openweathermap_api_key', 'openweathermap_api_key'), ('slack_app_api_key', 'slack_app_api_key'), ('slack_channel', 'slack_channel'), ('city_for_weather', 'city_for_weather'), ('website_url', 'website_url')], max_length=50, unique=True),
        ),
    ]
