# Generated by Django 2.2.7 on 2020-04-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200415_0952'),
        ('main', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_for_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Team'),
            preserve_default=False,
        ),
    ]
