# Generated by Django 2.2.7 on 2020-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200415_0952'),
        ('main', '0003_restaurant_restaurant_for_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('restaurant_for_team', 'restaurant_name')},
        ),
    ]
