# Generated by Django 2.2.7 on 2020-04-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200415_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
