# Generated by Django 2.2.7 on 2020-01-29 08:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absenceFrom', models.DateField(default=datetime.date.today)),
                ('absenceTo', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(choices=[('absent', 'absent'), ('i am out', 'do not care'), ('do not care', 'i am out')], default=[('absent', 'absent'), ('i am out', 'do not care'), ('do not care', 'i am out')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
