# Generated by Django 2.2.7 on 2020-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weather_group', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('icon_id', models.CharField(max_length=5)),
            ],
        ),
    ]
