# Generated by Django 2.2.7 on 2020-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0002_auto_20200130_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='key_name',
            field=models.CharField(choices=[('website_name', 'website_name'), ('background_image', 'background_image'), ('openweathermap_api_key', 'openweathermap_api_key'), ('slack_app_api_key', 'slack_app_api_key'), ('slack_channel', 'slack_channel'), ('city_for_weather', 'city_for_weather'), ('website_url', 'website_url'), ('timezone', 'timezone')], default=[('website_name', 'website_name'), ('background_image', 'background_image'), ('openweathermap_api_key', 'openweathermap_api_key'), ('slack_app_api_key', 'slack_app_api_key'), ('slack_channel', 'slack_channel'), ('city_for_weather', 'city_for_weather'), ('website_url', 'website_url'), ('timezone', 'timezone')], max_length=50, unique=True),
        ),
    ]
