name: Docker
on:
  push:
    
env:
  IMAGE_NAME: whereToEat
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  
jobs:  
  healthcheck:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Intall dependencies
        run: |
          pip3 install setuptools wheel
          pip3 install -r ./app/requirements.txt
          
      - name: Run test
        run: python3 ./app/manage.py test --no-input
  
  createBuildNumber:
    needs: healthcheck
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}        
    - name: Upload build number
      uses: actions/upload-artifact@v1
      with:
        name: BUILD_NUMBER
        path: BUILD_NUMBER
  
  buildAndPush:
    needs: createBuildNumber
    
    runs-on: ubuntu-latest

    steps:
    - name: Download build number
      uses: actions/download-artifact@v1
      with:
        name: BUILD_NUMBER
    - name: Restore build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      
    - uses: actions/checkout@v2

    - name: print
      run: $BUILD_NUMBER
      
    - name: Log into registry
      run: docker login -u ${{ secrets.DOCKERNAME }} -p ${{ secrets.DOCKERPASSWORD }}

    - name: Build images
      run: DATABASE_NAME=where_to_eat SQL_USER=where_to_eat SQL_PASSWORD=where_to_eat docker-compose -f docker-compose.prod.yml build

    - name: Push image
      if: github.ref == 'refs/heads/master'
      run: |
        DATABASE_NAME=where_to_eat SQL_USER=where_to_eat SQL_PASSWORD=where_to_eat docker-compose -f docker-compose.prod.yml push
