name: Docker

on:
  push:

env:
  IMAGE_NAME: whereToEat
  SECRET_KEY: ${{ secrets.secretKey }}
  
jobs:  
  healtcheck:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Intall dependencies
        run: |
          pip3 install setuptools wheel
          pip3 install -r ./app/requirements.txt
          pip3 install unittest-xml-reporting
          
      - name: Run test
        run: python3 ./app/manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
        
  buildAndPush:
    needs: healtcheck

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: docker login -u ${{ secrets.DOCKERNAME }} -p ${{ secrets.DOCKERPASSWORD }}

      - name: Build images
        run: docker-compose -f docker-compose.prod.yml build
        
      - name: Push image
        if: github.ref == 'refs/heads/master'
        run: |
          docker-compose push
