name: Check_And_Deploy
on:
  push:

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:  
  healthcheck:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Intall dependencies
        run: |
          pip3 install setuptools wheel
          pip3 install -r ./app/requirements.txt
      #create db file ??
      - name: create databse dir
        run: cd ./app/ && mkdir database
      - name: Run test
        run: cd ./app/ && python3 manage.py test --settings=LightningLunch.test_settings
  
  buildAndPush:
    needs: healthcheck
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      run: docker login -u ${{ secrets.DOCKERNAME }} -p ${{ secrets.DOCKERPASSWORD }}

    - name: Build images
      run: DATABASE_NAME=where_to_eat SQL_USER=where_to_eat SQL_PASSWORD=where_to_eat docker-compose -f docker-compose.prod.yml build

    - name: Push image
      if: github.ref == 'refs/heads/master'
      run: |
        DATABASE_NAME=where_to_eat SQL_USER=where_to_eat SQL_PASSWORD=where_to_eat docker-compose -f docker-compose.prod.yml push
